### ISSUE TITLE
Maven builds 0.1.0, 0.1.1 and 0.1.2 are missing META-INF/services

### ISSUE THREAD

**Issue by vovcacik** [kotcrab/callsuper-annotation#4]
The `javax.annotation.processing.Processor` file is missing in all your maven builds. I would prefer triggering your annotation processor via this file instead of configuring my pom.

**Comment by kotcrab** [comment]
Should be fine now, try snapshot and I can release it if you confirm it works.

**Comment by vovcacik** [comment]
It works, thank you. CallSuper is plug & play in 0.1.3-SNAPSHOT.

**Comment by kotcrab** [comment]
Great, I released 0.1.3.
